version: "3"

services:
  db:
    image: postgres
    container_name: DB_FastShop
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
  redis:
    image: redis:7
    container_name: Cache_FastShop
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
